# -*- mode: ruby -*-
# vi: set ft=ruby :

CTRL_MEMORY = 4096
CTRL_CPU = 2
WORKER_MEMORY = 6144
WORKER_CPU = 2
N_WORKERS = 2

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  # Control node
  config.vm.define "ctrl" do |ctrl|
    ctrl.vm.hostname = "ctrl"
    ctrl.vm.network "private_network", ip: "192.168.56.100"
    ctrl.vm.provider "virtualbox" do |v|
      v.memory = CTRL_MEMORY
      v.cpus = CTRL_CPU
    end

    ctrl.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/general.yaml"
      ansible.become = true
    end
    ctrl.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/ctrl.yaml"
      ansible.become = true
    end
  end

  # Worker nodes 
  (1..N_WORKERS).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{100 + i}"
      node.vm.provider "virtualbox" do |v|
        v.memory = WORKER_MEMORY
        v.cpus = WORKER_CPU
      end

      node.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbooks/general.yaml"
        ansible.become = true
      end
      # NOTE: node.yaml must be run separately after all VMs are up
      # See README for instructions
    end
  end
end