apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
    component: backend
spec:
  selector:
    app: app-service
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
