apiVersion: v1
kind: Service
metadata:
  name: app-frontend
  labels:
    app: app-frontend-serv
    component: frontend
spec:
  selector:
    app: app-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
