apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app: model-service
    component: ml-model
spec:
  selector:
    app: model-service
  ports:
    - name: http
      port: {{ .Values.model.service.port }}
      targetPort: {{ .Values.model.service.targetPort }}
