apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels: 
      app: app-service
  endpoints: 
    - port: http
      interval: 15s
      path: /sms/metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor-model
  labels: 
    release: myprom 
spec:
  selector:
    matchLabels: 
      app: model-service
  endpoints: 
    - port: http
      interval: 15s
      path: /sms/metrics

